import { copticLetter } from 'src/app/shared/types/coptic-letter';
import { copticLetters } from 'src/app/shared/constants/coptic-letters';

export const copticWordsList = [
  'ϣⲁ',
  'ϫⲉ',
  'ⲇⲉ',
  'ⲉⲓ',
  'ⲙⲓ',
  'ⲛⲓ',
  'ⲝⲓ',
  'ⲡⲉ',
  'ⲡⲓ',
  'ⲣⲏ',
  'ⲣⲟ',
  'ⲧⲉ',
  'ⲭⲁ',
  'ϣⲏⲡ',
  'ϧⲉⲛ',
  'ϩⲱⲛ',
  'ϫⲏⲕ',
  'ⲃⲱⲕ',
  'ⲉⲙⲓ',
  'ⲍⲱⲏ',
  'ⲏⲣⲡ',
  'ⲏⲧⲁ',
  'ⲑⲁⲓ',
  'ⲑⲱⲕ',
  'ⲙⲉⲓ',
  'ⲛⲁⲓ',
  'ⲛⲁⲛ',
  'ⲛⲁⲩ',
  'ⲛⲉⲙ',
  'ⲛⲏⲃ',
  'ⲛⲓⲙ',
  'ⲣⲁⲛ',
  'ϩⲟⲗϫ',
  'ϯϫⲟⲙ',
  'ⲁⲃⲃⲁ',
  'ⲁⲗⲗⲁ',
  'ⲁⲗⲫⲁ',
  'ⲁⲙⲏⲛ',
  'ⲁⲛⲟⲕ',
  'ⲇⲟⲝⲁ',
  'ⲉⲛⲉϩ',
  'ⲍⲉⲧⲁ',
  'ⲍⲱⲟⲛ',
  'Ⲑⲉⲟⲥ',
  'ⲑⲏⲧⲁ',
  'ⲓⲱⲧⲁ',
  'ⲕⲁⲧⲁ',
  'ⲗⲁⲟⲥ',
  'ⲗⲱⲃϣ',
  'ⲙⲏⲓϥ',
  'ⲙⲓⲥⲓ',
  'ⲙⲟϣⲓ',
  'ⲛ̀ϫⲉ',
  'ⲛ̀ⲧⲉ',
  'ⲛⲟⲃⲓ',
  'ⲛⲟⲩⲃ',
  'ⲟⲩⲏⲃ',
  'ⲟⲩⲟϩ',
  'ⲟⲩⲟⲛ',
  'ⲡⲁⲡⲁ',
  'ⲣⲁⲥϯ',
  'ⲣⲱⲙⲓ',
  'ⲥⲁⲣⲝ',
  'ⲧ̀ⲫⲉ',
  'ⲧⲱⲃϩ',
  'ⲩⲓⲟⲥ',
  'ⲯⲩⲭⲏ',
  'ϣ̀ⲑⲏⲛ',
  'ϩⲓϫⲉⲛ',
  'ⲁϥⲥⲱϯ',
  'ⲁⲅⲓⲟⲥ',
  'ⲁⲛⲍⲏⲃ',
  'ⲁⲝⲓⲟⲥ',
  'ⲃⲁⲧⲟⲥ',
  'Ⲇⲁⲩⲓⲇ',
  'ⲇⲉⲗⲧⲁ',
  'ⲇⲱⲣⲟⲛ',
  'ⲉ̀ⲃⲟⲗ',
  'ⲉⲧϧⲉⲛ',
  'ⲑ̀ⲙⲁⲩ',
  'ⲑⲉⲗⲏⲗ',
  'ⲑⲩⲥⲓⲁ',
  'Ⲓⲥⲁⲁⲕ',
  'ⲕⲁⲡⲡⲁ',
  'ⲗⲉⲩⲗⲁ',
  'Ⲙⲁⲣⲓⲁ',
  'ⲛ̀ϫⲟⲥ',
  'ⲛ̀ⲧⲁⲛ',
  'ⲛⲓⲃⲉⲛ',
  'ⲡ̀ⲱⲛϧ',
  'ⲡⲓⲱⲟⲩ',
  'Ⲣⲁⲕⲟϯ',
  'ⲥ̀ⲙⲟⲩ',
  'ⲧⲉⲛⲱϣ',
  'Ⲫ̀ⲓⲱⲧ',
  'ⲱⲙⲉⲅⲁ',
  'ϩⲩⲙⲛⲟⲥ',
  'Ⲇⲁⲛⲓⲏⲗ',
  'ⲇⲓⲁⲕⲟⲛ',
  'ⲇⲓⲕⲉⲟⲥ',
  'ⲇⲓⲡⲛⲟⲛ',
  'ⲉ̀ϧⲟⲩⲛ',
  'ⲉ̀ⲣⲱⲟⲩ',
  'ⲉⲑⲟⲩⲁⲃ',
  'ⲉⲝⲟⲇⲟⲥ',
  'Ⲏⲣⲱⲇⲏⲥ',
  'Ⲓⲟⲩⲇⲁⲥ',
  'ⲕⲉⲙⲕⲉⲙ',
  'ⲕⲩⲣⲓⲟⲥ',
  'ⲗⲁⲙⲡⲁⲥ',
  'ⲛⲁϩⲙⲉⲛ',
  'Ⲡ̀ϭⲟⲓⲥ',
  'Ⲡⲁⲩⲗⲟⲥ',
  'ⲡ̀ⲕⲁϩⲓ',
  'ⲡⲉⲕⲓⲱⲧ',
  'ⲡⲉⲛⲓⲱⲧ',
  'ⲧⲁⲥⲱⲛⲓ',
  'ⲩⲯⲓⲗⲟⲛ',
  'Ⲫ̀ⲛⲟⲩϯ',
  'ⲭ̀ⲟⲩⲁⲃ',
  'ⲁⲥⲑⲉⲛⲏⲥ',
  'ⲉⲝⲟⲩⲥⲓⲁ',
  'ⲕⲁⲑⲁⲣⲟⲥ',
  'Ⲗⲁⲍⲁⲣⲟⲥ',
  'ⲟⲙⲓⲕⲣⲟⲛ',
  'Ⲁⲛⲧⲱⲛⲓⲟⲥ',
  'Ⲍⲁⲭⲁⲣⲓⲁⲥ',
  'ⲡⲁⲣⲑⲉⲛⲟⲥ',
  'ⲡⲓⲥⲧⲁⲩⲣⲟⲥ',
  'ⲡⲓⲭⲣⲓⲥⲧⲟⲥ',
  'ⲥ̀ⲑⲟⲓⲛⲟⲩϥⲓ',
];

function createTransliterationFontMap(letters: copticLetter[]): {
  [key: string]: string;
} {
  const map: { [key: string]: string } = {};
  letters.forEach((letter) => {
    map[letter.uppercaseUnicode] = letter.copticFontMapping;
    map[letter.lowercaseUnicode] = letter.copticFontMapping;
  });
  return map;
}
const transliterationFontMap = createTransliterationFontMap(copticLetters);

function transliterate(word: string): string {
  return word
    .split('')
    .map((letter) => transliterationFontMap[letter] || letter)
    .join('');
}

export const copticWords = copticWordsList.map((word) => {
  return {
    unicodeWord: word,
    sound: `assets/words/${word}.mp3`,
    copticFontMapping: transliterate(word),
  };
});
